server:
  port: 28080
spring:
  profiles:
    active: h2 #可选值 h2、mysql, 使用H2可以免去连接数据库繁琐操作 临时体验管控台
  jackson:
    time-zone: GMT+8
    serialization:
      INDENT_OUTPUT: true #格式化JSON输出
      WRITE_DATES_AS_TIMESTAMPS: true #序列化时间格式时使用时间戳
    default-property-inclusion: non_null #响应时过滤null字段
  jpa:
    database: ${spring.profiles.active}
# 开启SQL参数显示
#logging:
#  level:
#    org.hibernate.SQL: debug
#    org.hibernate.engine.QueryParameters: debug
#    org.hibernate.engine.query.HQLQueryPlan: debug
#    org.hibernate.type.descriptor.sql.BasicBinder: trace
